name: graviton
description: "A physics simulation exploring gravitational dynamics and orbital mechanics."
publish_to: "none"
version: 1.0.0+2
repository: https://github.com/Chipper-Technologies/graviton
license: MIT

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  firebase_crashlytics: ^5.0.3
  firebase_remote_config: ^6.1.0
  flutter_svg: ^2.2.1
  package_info_plus: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  vector_math: ^2.2.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  adaptive_icon_background: "assets/images/app-logo-bg.png"
  adaptive_icon_foreground: "assets/images/app-logo-nobg.png"
  android: true
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0e091c"
  image: "assets/images/graviton-logo-transparent.png"
  color_dark: "#0e091c"
  image_dark: "assets/images/graviton-logo-transparent.png"
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: false
  web: false
