// Mocks generated by Mockito 5.4.6 from annotations
// in graviton/test/widgets/live_session/host_controls_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:graviton/core/enums/live_session_connection_status.dart' as _i4;
import 'package:graviton/models/firebase/live_session.dart' as _i3;
import 'package:graviton/models/firebase/simulation_snapshot.dart' as _i6;
import 'package:graviton/state/live_session_state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LiveSessionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSessionState extends _i1.Mock implements _i2.LiveSessionState {
  MockLiveSessionState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isHosting =>
      (super.noSuchMethod(Invocation.getter(#isHosting), returnValue: false)
          as bool);

  @override
  int get viewerCount =>
      (super.noSuchMethod(Invocation.getter(#viewerCount), returnValue: 0)
          as int);

  @override
  bool get isViewing =>
      (super.noSuchMethod(Invocation.getter(#isViewing), returnValue: false)
          as bool);

  @override
  List<_i3.LiveSession> get activeSessions =>
      (super.noSuchMethod(
            Invocation.getter(#activeSessions),
            returnValue: <_i3.LiveSession>[],
          )
          as List<_i3.LiveSession>);

  @override
  bool get isLoadingSessions =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingSessions),
            returnValue: false,
          )
          as bool);

  @override
  bool get isInSession =>
      (super.noSuchMethod(Invocation.getter(#isInSession), returnValue: false)
          as bool);

  @override
  _i4.LiveSessionConnectionStatus get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i4.LiveSessionConnectionStatus.disconnected,
          )
          as _i4.LiveSessionConnectionStatus);

  @override
  bool get hasRecentError =>
      (super.noSuchMethod(
            Invocation.getter(#hasRecentError),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> startHosting({
    required String? scenarioName,
    String? displayName,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startHosting, [], {
              #scenarioName: scenarioName,
              #displayName: displayName,
              #password: password,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateHostedSession({bool? isRunning, double? timeScale}) =>
      (super.noSuchMethod(
            Invocation.method(#updateHostedSession, [], {
              #isRunning: isRunning,
              #timeScale: timeScale,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopHosting() =>
      (super.noSuchMethod(
            Invocation.method(#stopHosting, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> startViewing(String? sessionId, {String? password}) =>
      (super.noSuchMethod(
            Invocation.method(
              #startViewing,
              [sessionId],
              {#password: password},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopViewing() =>
      (super.noSuchMethod(
            Invocation.method(#stopViewing, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> broadcastState(_i6.SimulationSnapshot? snapshot) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastState, [snapshot]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void startStateSync({
    void Function(_i6.SimulationSnapshot)? onSnapshotReceived,
  }) => super.noSuchMethod(
    Invocation.method(#startStateSync, [], {
      #onSnapshotReceived: onSnapshotReceived,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void stopStateSync() => super.noSuchMethod(
    Invocation.method(#stopStateSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void startSessionDiscovery() => super.noSuchMethod(
    Invocation.method(#startSessionDiscovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopSessionDiscovery({bool? notify = true}) => super.noSuchMethod(
    Invocation.method(#stopSessionDiscovery, [], {#notify: notify}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> cleanup() =>
      (super.noSuchMethod(
            Invocation.method(#cleanup, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
