// Mocks generated by Mockito 5.4.6 from annotations
// in graviton/test/widgets/live_session/host_controls_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:graviton/core/enums/live_session_connection_status.dart' as _i7;
import 'package:graviton/core/enums/premium_tier.dart' as _i12;
import 'package:graviton/features/premium/domain/premium_feature.dart' as _i13;
import 'package:graviton/features/premium/domain/premium_limits.dart' as _i2;
import 'package:graviton/features/premium/domain/premium_pricing.dart' as _i3;
import 'package:graviton/features/premium/domain/usage_data.dart' as _i4;
import 'package:graviton/features/premium/presentation/premium_state.dart'
    as _i11;
import 'package:graviton/models/firebase/live_session.dart' as _i6;
import 'package:graviton/models/firebase/simulation_snapshot.dart' as _i9;
import 'package:graviton/state/live_session_state.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:purchases_flutter/purchases_flutter.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePremiumLimits_0 extends _i1.SmartFake implements _i2.PremiumLimits {
  _FakePremiumLimits_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePremiumPricing_1 extends _i1.SmartFake
    implements _i3.PremiumPricing {
  _FakePremiumPricing_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsageData_2 extends _i1.SmartFake implements _i4.UsageData {
  _FakeUsageData_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LiveSessionState].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveSessionState extends _i1.Mock implements _i5.LiveSessionState {
  MockLiveSessionState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isHosting =>
      (super.noSuchMethod(Invocation.getter(#isHosting), returnValue: false)
          as bool);

  @override
  int get viewerCount =>
      (super.noSuchMethod(Invocation.getter(#viewerCount), returnValue: 0)
          as int);

  @override
  bool get isViewing =>
      (super.noSuchMethod(Invocation.getter(#isViewing), returnValue: false)
          as bool);

  @override
  List<_i6.LiveSession> get activeSessions =>
      (super.noSuchMethod(
            Invocation.getter(#activeSessions),
            returnValue: <_i6.LiveSession>[],
          )
          as List<_i6.LiveSession>);

  @override
  bool get isLoadingSessions =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingSessions),
            returnValue: false,
          )
          as bool);

  @override
  bool get isInSession =>
      (super.noSuchMethod(Invocation.getter(#isInSession), returnValue: false)
          as bool);

  @override
  _i7.LiveSessionConnectionStatus get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i7.LiveSessionConnectionStatus.disconnected,
          )
          as _i7.LiveSessionConnectionStatus);

  @override
  bool get hasRecentError =>
      (super.noSuchMethod(
            Invocation.getter(#hasRecentError),
            returnValue: false,
          )
          as bool);

  @override
  bool get syncCameraWithViewers =>
      (super.noSuchMethod(
            Invocation.getter(#syncCameraWithViewers),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSyncCameraWithViewers(bool? value) => super.noSuchMethod(
    Invocation.method(#setSyncCameraWithViewers, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> startHosting({
    required String? scenarioName,
    String? displayName,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startHosting, [], {
              #scenarioName: scenarioName,
              #displayName: displayName,
              #password: password,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> updateHostedSession({
    bool? isRunning,
    double? timeScale,
    String? scenarioName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateHostedSession, [], {
              #isRunning: isRunning,
              #timeScale: timeScale,
              #scenarioName: scenarioName,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> stopHosting() =>
      (super.noSuchMethod(
            Invocation.method(#stopHosting, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> startViewing(String? sessionId, {String? password}) =>
      (super.noSuchMethod(
            Invocation.method(
              #startViewing,
              [sessionId],
              {#password: password},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> stopViewing() =>
      (super.noSuchMethod(
            Invocation.method(#stopViewing, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> broadcastState(_i9.SimulationSnapshot? snapshot) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastState, [snapshot]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void startStateSync({
    void Function(_i9.SimulationSnapshot)? onSnapshotReceived,
  }) => super.noSuchMethod(
    Invocation.method(#startStateSync, [], {
      #onSnapshotReceived: onSnapshotReceived,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void stopStateSync() => super.noSuchMethod(
    Invocation.method(#stopStateSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void startSessionDiscovery() => super.noSuchMethod(
    Invocation.method(#startSessionDiscovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopSessionDiscovery({bool? notify = true}) => super.noSuchMethod(
    Invocation.method(#stopSessionDiscovery, [], {#notify: notify}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> cleanup() =>
      (super.noSuchMethod(
            Invocation.method(#cleanup, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PremiumState].
///
/// See the documentation for Mockito's code generation for more information.
class MockPremiumState extends _i1.Mock implements _i11.PremiumState {
  MockPremiumState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  _i12.PremiumTier get tier =>
      (super.noSuchMethod(
            Invocation.getter(#tier),
            returnValue: _i12.PremiumTier.free,
          )
          as _i12.PremiumTier);

  @override
  bool get hasPremiumAccess =>
      (super.noSuchMethod(
            Invocation.getter(#hasPremiumAccess),
            returnValue: false,
          )
          as bool);

  @override
  bool get isFreeTier =>
      (super.noSuchMethod(Invocation.getter(#isFreeTier), returnValue: false)
          as bool);

  @override
  _i2.PremiumLimits get limits =>
      (super.noSuchMethod(
            Invocation.getter(#limits),
            returnValue: _FakePremiumLimits_0(this, Invocation.getter(#limits)),
          )
          as _i2.PremiumLimits);

  @override
  _i3.PremiumPricing get pricing =>
      (super.noSuchMethod(
            Invocation.getter(#pricing),
            returnValue: _FakePremiumPricing_1(
              this,
              Invocation.getter(#pricing),
            ),
          )
          as _i3.PremiumPricing);

  @override
  _i4.UsageData get usageData =>
      (super.noSuchMethod(
            Invocation.getter(#usageData),
            returnValue: _FakeUsageData_2(this, Invocation.getter(#usageData)),
          )
          as _i4.UsageData);

  @override
  Duration get remainingSessionTime =>
      (super.noSuchMethod(
            Invocation.getter(#remainingSessionTime),
            returnValue: _FakeDuration_3(
              this,
              Invocation.getter(#remainingSessionTime),
            ),
          )
          as Duration);

  @override
  bool get sessionExpired =>
      (super.noSuchMethod(
            Invocation.getter(#sessionExpired),
            returnValue: false,
          )
          as bool);

  @override
  bool get canStartSession =>
      (super.noSuchMethod(
            Invocation.getter(#canStartSession),
            returnValue: false,
          )
          as bool);

  @override
  int get sessionsRemainingToday =>
      (super.noSuchMethod(
            Invocation.getter(#sessionsRemainingToday),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasExceededDurationLimit =>
      (super.noSuchMethod(
            Invocation.getter(#hasExceededDurationLimit),
            returnValue: false,
          )
          as bool);

  @override
  int get maxViewers =>
      (super.noSuchMethod(Invocation.getter(#maxViewers), returnValue: 0)
          as int);

  @override
  bool get shouldShowTimeWarning =>
      (super.noSuchMethod(
            Invocation.getter(#shouldShowTimeWarning),
            returnValue: false,
          )
          as bool);

  @override
  set onSessionExpired(_i10.VoidCallback? value) => super.noSuchMethod(
    Invocation.setter(#onSessionExpired, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> login(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#login, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshPremiumStatus() =>
      (super.noSuchMethod(
            Invocation.method(#refreshPremiumStatus, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool doesFeatureRequirePremium(_i13.PremiumFeature? feature) =>
      (super.noSuchMethod(
            Invocation.method(#doesFeatureRequirePremium, [feature]),
            returnValue: false,
          )
          as bool);

  @override
  bool canUseFeature(_i13.PremiumFeature? feature) =>
      (super.noSuchMethod(
            Invocation.method(#canUseFeature, [feature]),
            returnValue: false,
          )
          as bool);

  @override
  void startSessionTracking() => super.noSuchMethod(
    Invocation.method(#startSessionTracking, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopSessionTracking() => super.noSuchMethod(
    Invocation.method(#stopSessionTracking, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSessionExpired() => super.noSuchMethod(
    Invocation.method(#resetSessionExpired, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> purchasePackage(_i14.Package? package) =>
      (super.noSuchMethod(
            Invocation.method(#purchasePackage, [package]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  String formatRemainingTime() =>
      (super.noSuchMethod(
            Invocation.method(#formatRemainingTime, []),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.method(#formatRemainingTime, []),
            ),
          )
          as String);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
