// Mocks generated by Mockito 5.4.6 from annotations
// in graviton/test/widgets/maintenance_dialog_mocked_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:graviton/enums/ab_test_group.dart' as _i4;
import 'package:graviton/enums/user_behavior_tracking_mode.dart' as _i3;
import 'package:graviton/services/remote_config_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i2.RemoteConfigService {
  MockRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get analyticsSamplingRate =>
      (super.noSuchMethod(
            Invocation.getter(#analyticsSamplingRate),
            returnValue: 0.0,
          )
          as double);

  @override
  bool get crashReportingEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#crashReportingEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get performanceMonitoringEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#performanceMonitoringEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i3.UserBehaviorTrackingMode get userBehaviorTracking =>
      (super.noSuchMethod(
            Invocation.getter(#userBehaviorTracking),
            returnValue: _i3.UserBehaviorTrackingMode.full,
          )
          as _i3.UserBehaviorTrackingMode);

  @override
  _i4.ABTestGroup get abTestGroup =>
      (super.noSuchMethod(
            Invocation.getter(#abTestGroup),
            returnValue: _i4.ABTestGroup.control,
          )
          as _i4.ABTestGroup);

  @override
  bool get maintenanceMode =>
      (super.noSuchMethod(
            Invocation.getter(#maintenanceMode),
            returnValue: false,
          )
          as bool);

  @override
  String get maintenanceMessage =>
      (super.noSuchMethod(
            Invocation.getter(#maintenanceMessage),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#maintenanceMessage),
            ),
          )
          as String);

  @override
  bool get newsBannerEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#newsBannerEnabled),
            returnValue: false,
          )
          as bool);

  @override
  String get newsBannerText =>
      (super.noSuchMethod(
            Invocation.getter(#newsBannerText),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#newsBannerText),
            ),
          )
          as String);

  @override
  String get emergencyNotification =>
      (super.noSuchMethod(
            Invocation.getter(#emergencyNotification),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#emergencyNotification),
            ),
          )
          as String);

  @override
  bool get isUserBehaviorTrackingEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isUserBehaviorTrackingEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get isEnhancedTrackingEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isEnhancedTrackingEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasActiveNotification =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveNotification),
            returnValue: false,
          )
          as bool);

  @override
  String get activeNotificationText =>
      (super.noSuchMethod(
            Invocation.getter(#activeNotificationText),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#activeNotificationText),
            ),
          )
          as String);

  @override
  bool get isEmergencyNotification =>
      (super.noSuchMethod(
            Invocation.getter(#isEmergencyNotification),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool shouldSampleAnalytics() =>
      (super.noSuchMethod(
            Invocation.method(#shouldSampleAnalytics, []),
            returnValue: false,
          )
          as bool);
}
